`ifndef CANNY_SEQ_ITEM_SV
`define CANNY_SEQ_ITEM_SV

import uvm_pkg::*;
`include "uvm_macros.svh"


// ============================================================
// Transaction types used by Canny sequences and the driver
// ============================================================

typedef enum {
  AXI_LITE_WRITE,
  AXI_LITE_READ,
  AXI_FULL_WRITE_BURST,
  AXI_FULL_READ_BURST,
  START_PROCESSING,
  WAIT_READY
} canny_trans_type_t;


// ============================================================
// Canny sequence item
// ============================================================

class canny_seq_item extends uvm_sequence_item;

  // Requested transaction type.
  rand canny_trans_type_t trans_type;


  // ==========================================================
  // Shared address and data fields.
  // AXI-Lite uses addr[4:0]; AXI-Full uses addr[18:0].
  // ==========================================================

  rand bit [31:0] addr;
  rand bit [31:0] data;


  // ==========================================================
  // AXI-Full burst length in 32-bit beats:
  //   1   -> ARLEN/AWLEN = 0
  //   256 -> ARLEN/AWLEN = 255
  // ==========================================================

  rand int unsigned burst_len;


  // Write-burst payload generated by the sequence.
  rand bit [31:0] burst_data[];


  // AXI-Full read data returned by the driver.
  bit [31:0] read_burst_data[];


  // AXI-Lite read data returned by the driver.
  bit [31:0] read_data;


  // ==========================================================
  // AXI burst-length constraint
  // ==========================================================

  constraint valid_burst_len_c {
    if (
      trans_type inside {
        AXI_FULL_WRITE_BURST,
        AXI_FULL_READ_BURST
      }
    ) {
      burst_len inside {[1:256]};
    }
  }


  // ==========================================================
  // UVM factory registration
  // ==========================================================

  `uvm_object_utils_begin(canny_seq_item)

    `uvm_field_enum(
      canny_trans_type_t,
      trans_type,
      UVM_ALL_ON
    )

    `uvm_field_int(
      addr,
      UVM_ALL_ON
    )

    `uvm_field_int(
      data,
      UVM_ALL_ON
    )

    `uvm_field_int(
      burst_len,
      UVM_ALL_ON
    )

    `uvm_field_array_int(
      burst_data,
      UVM_ALL_ON
    )

    `uvm_field_array_int(
      read_burst_data,
      UVM_ALL_ON
    )

    `uvm_field_int(
      read_data,
      UVM_ALL_ON
    )

  `uvm_object_utils_end


  // ==========================================================
  // Constructor
  // ==========================================================

  function new(
    input string name = "canny_seq_item"
  );

    super.new(name);

  endfunction

endclass

`endif